# Your project's server URL
URL: "https://sixteenbit.ddev.site"

# Theme strings used in the `rename` gulp task
THEME:
  ## The current strings in the theme
  CURRENT:
    name: "Starting Line"
    slug: "starting-line"
    prefix: "starting_line_"
    class: "SL_"
  ## The strings to rename in the theme
  NEW:
    name: "Starting Line"
    slug: "starting-line"
    prefix: "starting_line_"
    class: "SL_"

# Used in the theme .pot file for translation
POT:
  domain: 'starting-line'
  package: 'starting-line'

# Gulp will reference these paths when it copies files
PATHS:
  php:
    - "./*.php"
    - "./**/*.php"
  images:
    - "src/img/**/*"
  sass:
    foundation:
      - "node_modules/foundation-sites/scss"
    fontawesome:
      - "node_modules/@fortawesome/fontawesome-free/scss"
  javascript:
    vendors:
      - "node_modules/what-input/dist/what-input.js"
      - "node_modules/foundation-sites/dist/js/foundation.js"
    theme:
      - "src/js/customizer.js"
    custom:
      - "src/js/**/_*.js"
  fonts:
    fontawesome:
      - "node_modules/@fortawesome/fontawesome-free/webfonts/*"
